#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}_${ARCH}}
REPO=${REPO:-rancher}

cp ../bin/plugin-manager ../bin/oldvethsync .

IMAGE=${REPO}/network-manager:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
